version: '2'
services:
  npm:
    image: node
    env_file: .env
    working_dir: "${WDIR}"
    entrypoint: npm
    command: run dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ".:${WDIR}"
