version: '2'
services:
  npmrun:
    image: node
    env_file: .env
    working_dir: "${WDIR}"
    entrypoint: npm run
    command: dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ".:${WDIR}"
